### ISSUE TITLE
Error initializing WhatsApp client

### ISSUE THREAD

**Issue by soulhd** [hacxk/easy-baileys#1]
Tried starting a project based on every of your examples with MongoDB, MySQL, MultiFile auth but it spat same error, like:

```
const WhatsAppClient = require('easy-baileys');

(async () => {
    try {
        const customOptions = {
            browser: ["Ubuntu", "Chrome", "20.0.04"],
            printQRInTerminal: true,
            mobile: false,
        };

        const client = await WhatsAppClient.createMultiAuth('./hacxk', customOptions);
        const conn = await client.getSocket();

        conn.ev.on("messages.upsert", async ({ messages }) => {
            for (const m of messages) {
                if (m.message?.conversation.toLowerCase() === 'hi') {
                    await conn.reply(m, 'Hello! 👋');
                }
            }
        });

    } catch (error) {
        console.error('Error initializing WhatsApp client:', error.message);
    }
})();
```

gave me this error:

`Error initializing WhatsApp client: WhatsAppClient.createMultiAuth is not a function`

Any suggestions?

**Comment by hacxk** [comment]
are you updated

**Comment by hacxk** [comment]
```Javascript

const { WhatsAppClient } = require('easy-baileys');

(async () => {
    try {
        const customOptions = {
            browser: ["Ubuntu", "Chrome", "20.0.04"],
            printQRInTerminal: true,
            mobile: false,
        };

        const client = await WhatsAppClient.createMultiAuth('./hacxk', customOptions);
        const conn = await client.getSocket();

        conn.ev.on("messages.upsert", async ({ messages }) => {
            for (const m of messages) {
                if (m.message?.conversation.toLowerCase() === 'hi') {
                    await conn.reply(m, 'Hello! 👋');
                }
            }
        });

    } catch (error) {
        console.error('Error initializing WhatsApp client:', error.message);
    }
})();```

**Comment by hacxk** [comment]
if still not work updated to latest version 1.1.23 and implement this code 

> ```js
> const { WhatsAppClient } = require('easy-baileys');
> 
> (async () => {
>     try {
>         const customOptions = {
>             browser: ["Ubuntu", "Chrome", "20.0.04"],
>             printQRInTerminal: true,
>             mobile: false,
>         };
> 
>         const client = await WhatsAppClient.createMultiAuth('./hacxk', customOptions);
>         const conn = await client.getSocket();
> 
>         conn.ev.on("messages.upsert", async ({ messages }) => {
>             for (const m of messages) {
>                 if (m.message?.conversation.toLowerCase() === 'hi') {
>                     await conn.reply(m, 'Hello! 👋');
>                 }
>             }
>         });
> 
>     } catch (error) {
>         console.error('Error initializing WhatsApp client:', error.message);
>     }
> })();```
> ```

**Comment by hacxk** [comment]
i am now close this issue if any still problem open it!

**Comment by soulhd** [comment]
> if still not work updated to latest version 1.1.23 and implement this code
> 
> > ```js
> > const { WhatsAppClient } = require('easy-baileys');
> > 
> > (async () => {
> >     try {
> >         const customOptions = {
> >             browser: ["Ubuntu", "Chrome", "20.0.04"],
> >             printQRInTerminal: true,
> >             mobile: false,
> >         };
> > 
> >         const client = await WhatsAppClient.createMultiAuth('./hacxk', customOptions);
> >         const conn = await client.getSocket();
> > 
> >         conn.ev.on("messages.upsert", async ({ messages }) => {
> >             for (const m of messages) {
> >                 if (m.message?.conversation.toLowerCase() === 'hi') {
> >                     await conn.reply(m, 'Hello! 👋');
> >                 }
> >             }
> >         });
> > 
> >     } catch (error) {
> >         console.error('Error initializing WhatsApp client:', error.message);
> >     }
> > })();```
> > ```

Yes, this one works for me. Thanks

**Comment by hacxk** [comment]
> > if still not work updated to latest version 1.1.23 and implement this code
> > > ```js
> > > const { WhatsAppClient } = require('easy-baileys');
> > > 
> > > (async () => {
> > >     try {
> > >         const customOptions = {
> > >             browser: ["Ubuntu", "Chrome", "20.0.04"],
> > >             printQRInTerminal: true,
> > >             mobile: false,
> > >         };
> > > 
> > >         const client = await WhatsAppClient.createMultiAuth('./hacxk', customOptions);
> > >         const conn = await client.getSocket();
> > > 
> > >         conn.ev.on("messages.upsert", async ({ messages }) => {
> > >             for (const m of messages) {
> > >                 if (m.message?.conversation.toLowerCase() === 'hi') {
> > >                     await conn.reply(m, 'Hello! 👋');
> > >                 }
> > >             }
> > >         });
> > > 
> > >     } catch (error) {
> > >         console.error('Error initializing WhatsApp client:', error.message);
> > >     }
> > > })();```
> > > ```
> 
> Yes, this one works for me. Thanks

**Happy Coding**

If u can support me give one star to this repo thanks for using my package
