### ISSUE TITLE
WhatsAppClient.createMongoAuth is not a function

### ISSUE THREAD

**Issue by marcelotadeujr** [hacxk/easy-baileys#2]
Hi, first of all thanks for awesome implementation you did!

So, im trying to run Easy-Baileys from your exemple folder but i'm getting error:
![image](https://github.com/user-attachments/assets/a6d281f2-6429-4c65-afd1-8748516c8629)

In that case i'm trying to use MongoDB auth, but the same error occour on multi-file/mysql init.

My code snipet:
![image](https://github.com/user-attachments/assets/475d659d-b77d-4849-9ea5-69c45d1139af)

Thanks.

**Comment by hacxk** [comment]
Hey [marcelotadeujr](https://github.com/marcelotadeujr),

Thanks a bunch for the kind words! 😄

About that error, I'll definitely take a look. It's strange that it's happening with MongoDB and the other setups too.

I'll check the code and see what's going on. If you have any other info or ways to make the error happen again, let me know. It'll help me find and fix the problem quicker!

Thanks again for getting in touch, and I'll keep you in the loop!

Cheers,
Zaid

**Comment by hacxk** [comment]
> Hi, first of all thanks for awesome implementation you did!
> 
> So, im trying to run Easy-Baileys from your exemple folder but i'm getting error: ![image](https://private-user-images.githubusercontent.com/7066098/356373764-a6d281f2-6429-4c65-afd1-8748516c8629.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNzcyMTIsIm5iZiI6MTcyMzE3NjkxMiwicGF0aCI6Ii83MDY2MDk4LzM1NjM3Mzc2NC1hNmQyODFmMi02NDI5LTRjNjUtYWZkMS04NzQ4NTE2Yzg2MjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDlUMDQxNTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTYzYjczYmE3YjM2Nzg4NzNiY2I1ZjMzMWJlZThiYTQ3NjEzMWY1Yjk1MDE0ODU0YjlhMWIxOWJkZGExZWYwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.T5eTaVZm0n4fy27-T_YCu--8i3RL6lKzntwObGqnWHs)
> 
> In that case i'm trying to use MongoDB auth, but the same error occour on multi-file/mysql init.
> 
> My code snipet: ![image](https://private-user-images.githubusercontent.com/7066098/356374041-475d659d-b77d-4849-9ea5-69c45d1139af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNzcyMTIsIm5iZiI6MTcyMzE3NjkxMiwicGF0aCI6Ii83MDY2MDk4LzM1NjM3NDA0MS00NzVkNjU5ZC1iNzdkLTQ4NDktOWVhNS02OWM0NWQxMTM5YWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDlUMDQxNTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGFhM2U2NjQxODdiZTI0YWY0MmQyNzFhMGRhYTBkYTU3OWMyNzVhY2I0N2UzMmEwYzg2NWJjMGQzNDZiYzdkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.n_ifdQDbwFrB4wtdRTUTelVESnYL51iEtdTXJEYbL0w)
> 
> Thanks.

**Fixed:** 

```js
const { WhatsAppClient } = require('easy-baileys');

const customOptions = {
    browser: ["Ubuntu", "Chrome", "20.0.04"],
    printQRInTerminal: true, // Set to true for QR code in terminal
    mobile: false,
};

async function main() {
    try {
        // Initialize WhatsAppClient with MongoDB authentication
        const clientMongo = await WhatsAppClient.create("mongo", 'YOUR MONGO DB URI', customOptions);
        const sockMongo = await clientMongo.getSocket();

        // Example event listener for incoming messages
        sockMongo.ev.on("messages.upsert", async ({ messages }) => {
            for (const m of messages) {
                console.log(m)
                if (m.message?.conversation.toLowerCase() === 'hi') {
                    await sockMongo.reply(m, 'Hello! 👋');
                    sockMongo.sendImage()
                }
            }
        });

    } catch (error) {
        console.error('Error initializing WhatsApp client with MongoDB authentication:', error.message);
    }
}

main()
```
