### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by OfficialDevGithub** [hacxk/easy-baileys#3]
Error initializing WhatsApp client: WhatsAppClient.createMultiAuth is not a function

**Comment by hacxk** [comment]
Update and use this

```js
const { WhatsAppClient } = require('easy-baileys');

const customOptions = {
  browser: ["Ubuntu", "Chrome", "20.0.04"],
  printQRInTerminal: false, // Set to true for QR code in terminal
  mobile: false,
};

(async () => {
  try {
    // Initialize WhatsAppClient with MultiFile authentication
    const clientMulti = await WhatsAppClient.create("multi", './authFiles', customOptions);
    const sockMulti = await clientMulti.getSocket();

    // Example event listener for incoming messages
    sockMulti.ev.on("messages.upsert", async ({ messages }) => {
      for (const m of messages) {
        if (m.message?.conversation.toLowerCase() === 'hi') {
          await sockMulti.reply(m, 'Hello! 👋');
        }
      }
    });

  } catch (error) {
    console.error('Error initializing WhatsApp client with MultiFile authentication:', error.message);
  }
})();
```

**Comment by OfficialDevGithub** [comment]
{"level":30,"time":"2024-09-22T21:11:41.052Z","pid":19811,"hostname":"localhost","class":"baileys","browser":["Ubuntu","Chrome","20.0.04"],"helloMsg":{"clientHello":{"ephemeral":"Mp3uNjYQiPUoCxdxiZDN1qyU22s1oQSCe7xHOY2+eBc="}},"msg":"connected to WA"}
{"level":30,"time":"2024-09-22T21:11:41.557Z","pid":19811,"hostname":"localhost","class":"baileys","node":{"passive":false,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":3000,"tertiary":1015901307},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","devicePairingData":{"eRegid":"AAAAKA==","eKeytype":"BQ==","eIdent":"x9D5Om1Ph4Gs3lKSZ4yF1le5JDNoTt2iSmPJ3j8k2gc=","eSkeyId":"AAAB","eSkeyVal":"cblqcLs8F9p8zJbauX5Ht6EbIqgwCuoSWUUN1+SeCmM=","eSkeySig":"MD9P2rgdWQV8jidKnhUoacHA5rTn7ifJ0iYQn+8cM1dSldkFzTiKTuGrkE7OEUjKrgB/BpoDFcXdoRtfFuhgBw==","buildHash":"XU5Elvgegz+f9FOU5QBeaw==","deviceProps":"CgZVYnVudHUYASAA"}},"msg":"not logged in, attempting registration..."}

**Comment by OfficialDevGithub** [comment]
How to use it?

**Comment by hacxk** [comment]
yeah it's working to get QR Install qr code terminal ```npm install qrcode-terminal```
